"use client";

export default function FeaturesSection() {
  return (
    <section className="section is-inner-section-inside"><div className="inner-section is-ai-magic-marquee"><div className="w-layout-blockcontainer container-default w-container"><div className="w-layout-grid glass-marquee-grid"><div id="w-node-e2d4d525-99f1-3c49-b11b-740b86da8aba-889bb96a" className="gtp-container-wrapper"><div data-w-id="f90dde17-7d50-c32e-250b-5ebb422dfbd8" style={{ opacity: "0" }} className="marquee-vertical-wrapper is-glass-marquee-vertical"><div data-w-id="cb3132bf-fb06-2916-f3e4-7b82383ff37d" className="marquee-vertical-columns-wrapper is-glass-marquee-vertical"><div className="marquee-vertical-column is-glass-marquee-vertical marquee-animation"><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea679057a7f47b8b1440f_3d-cube-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="432" alt="3D Cube Icon Marquee Builderai Webflow Template | BRIX Template   
" className="position-relative-z-index-1"/></div></div><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea6791f06b79c415b37f2_circle-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Circle Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea679057a7f47b8b1442a_rectangle-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Rectangle Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div></div><div className="marquee-vertical-column is-glass-marquee-vertical marquee-animation"><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea679057a7f47b8b1440f_3d-cube-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="432" alt="3D Cube Icon Marquee Builderai Webflow Template | BRIX Template   
" className="position-relative-z-index-1"/></div></div><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea6791f06b79c415b37f2_circle-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Circle Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea679057a7f47b8b1442a_rectangle-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Rectangle Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div></div><div className="marquee-vertical-column is-glass-marquee-vertical marquee-animation"><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea679057a7f47b8b1440f_3d-cube-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="432" alt="3D Cube Icon Marquee Builderai Webflow Template | BRIX Template   
" className="position-relative-z-index-1"/></div></div><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea6791f06b79c415b37f2_circle-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Circle Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea679057a7f47b8b1442a_rectangle-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Rectangle Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div></div></div><div data-w-id="1b6acd91-874d-9c21-049a-819a49722235" className="marquee-vertical-columns-wrapper is-glass-marquee-vertical"><div className="marquee-vertical-column is-glass-marquee-vertical marquee-animation"><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea6794fd12e774da97b00_ring-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Ring Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea679d99dd2a05bf28ed3_triangle-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Triangle Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea67905add1aa28235aae_node-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Node Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div></div><div className="marquee-vertical-column is-glass-marquee-vertical marquee-animation"><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea6794fd12e774da97b00_ring-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Ring Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea679d99dd2a05bf28ed3_triangle-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Triangle Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea67905add1aa28235aae_node-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Node Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div></div><div className="marquee-vertical-column is-glass-marquee-vertical marquee-animation"><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea6794fd12e774da97b00_ring-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Ring Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea679d99dd2a05bf28ed3_triangle-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Triangle Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea67905add1aa28235aae_node-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Node Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div></div></div><div data-w-id="d823e988-d82c-0338-4e9f-f681af959c53" className="marquee-vertical-columns-wrapper is-glass-marquee-vertical"><div className="marquee-vertical-column is-glass-marquee-vertical marquee-animation"><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea679d99dd2a05bf28ed3_triangle-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Triangle Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea67905add1aa28235aae_node-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Node Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea679d795e8bd46e8a69b_pearlescent-curve-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Pearlescent Curve Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div></div><div className="marquee-vertical-column is-glass-marquee-vertical marquee-animation"><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea679d99dd2a05bf28ed3_triangle-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Triangle Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea67905add1aa28235aae_node-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Node Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea679d795e8bd46e8a69b_pearlescent-curve-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Pearlescent Curve Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div></div><div className="marquee-vertical-column is-glass-marquee-vertical marquee-animation"><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea679d99dd2a05bf28ed3_triangle-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Triangle Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea67905add1aa28235aae_node-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Node Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div><div className="marquee-vertical-item"><div className="glass-card"><div className="glass-card-overlay"></div><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68dea679d795e8bd46e8a69b_pearlescent-curve-icon-marquee-builderai-webflow-template.png" loading="lazy" width="406" height="431" alt="Pearlescent Curve Icon Marquee Builderai Webflow Template | BRIX Template  
" className="position-relative-z-index-1"/></div></div></div></div></div><div className="gtp-container"><div id="w-node-_7e37c262-7ce1-a453-a11d-ce1b3afba667-3afba667" data-w-id="7e37c262-7ce1-a453-a11d-ce1b3afba667" className="gpt-chat-window"><div className="gpt-chat-promp-window"><div className="gpt-chat-promp">Ask Builder AI to create a mobile app that...</div><div className="gpt-chat-menu-wrapper"><div className="gtp-chat-menu"><div className="gtp-chat-menu-logo"><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68d5a8ad6d1f2fe4c6413a31_gpt-logo-small-builderai-webflow-template.svg" loading="lazy" width="18" height="18" alt="Gpt Logo Small Builderai Webflow Template | BRIX Template  
"/><div>GPT-5</div></div><svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 12 13" fill="none" className="gtp-chat-menu-arrow"><path d="M9.29919 4.75L5.9992 8.25L2.69922 4.75" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"></path></svg></div><div className="gtp-chat-menu-button"><svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 13 13" fill="none" className="gtp-chat-menu-button-arrow"><path d="M1 6.36816L11.9998 6.36816" stroke="currentColor" strokeWidth="2" strokeLinecap="round"></path><path d="M6.86719 1.2373L11.9993 6.36942" stroke="currentColor" strokeWidth="2" strokeLinecap="round"></path><path d="M6.86719 11.5L11.9993 6.36788" stroke="currentColor" strokeWidth="2" strokeLinecap="round"></path></svg></div></div></div><div className="gtp-chat-features"><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68d5aa052caaeea89e73f99d_attach-image-builderai-webflow-template.svg" loading="lazy" width="90" height="17" alt="Attach Image Builderai Webflow Template | BRIX Template  
"/><img src="https://cdn.prod.website-files.com/68cc21ec139e2486889bb97d/68d5aa057b89a7acaf7f4693_import-from-figma-builderai-webflow-template.svg" loading="lazy" width="117" height="17" alt="Import From Figma Builderai Webflow Template | BRIX Template  
"/></div></div></div></div><div id="w-node-fc5aeea7-a1ec-6037-1021-46b65ce666e8-889bb96a" className="inner-container is-38ch is-100-tablet"><div className="text-align-center-tablet"><h2 data-w-id="26eee2f0-9732-9670-b028-3364bad544e7" style={{ opacity: "0", webkitTransform: "translate3d(0, 50px, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)", mozTransform: "translate3d(0, 50px, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)", msTransform: "translate3d(0, 50px, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)", transform: "translate3d(0, 50px, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)" }} className="display-9">Start creating with AI magic</h2><p data-w-id="7f22974c-8dd6-bc6b-0915-f1f72a2199c8" style={{ opacity: "0", webkitTransform: "translate3d(0, 50px, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)", mozTransform: "translate3d(0, 50px, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)", msTransform: "translate3d(0, 50px, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)", transform: "translate3d(0, 50px, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)" }} className="mg-vertical-4xs---2xs">Lorem ipsum dolor sit amet consectetur lobortis sed ut urna orci libero eu laoreet sed augue leo placerat.</p></div><div data-w-id="a4c55560-8950-95a0-9946-3b67a9ea52bc" style={{ opacity: "0" }} className="flex-horizontal-tablet"><a data-wf--ui-element---button-global--button---variant="is-accent" data-w-id="24618eba-fe56-17fe-58b2-dede99cf8d03" href="/company-pages/pricing" className="button w-inline-block"><div className="button-group"><div className="item-icon-left"><div className="custom-icon-set"></div></div><div>Start creating</div></div><div className="button-group absolute"><div className="item-icon-left"><div className="custom-icon-set"></div></div><div>Start creating</div></div></a></div></div></div></div></div></section>
  );
}
